In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data Extraction

In [2]:
import pandas as pd

data = "/content/drive/MyDrive/Colab Notebooks/Dataset/twitter_training.csv"
data = pd.read_csv(data)
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [24]:
pd.set_option('display.max_colwidth', None)

# 1. Find a specific word on the twitter content and number of occurrences

In [25]:
# Check for 'hello' word
import re

word_count = data.iloc[:, 3].apply(lambda x : len(re.findall('hello', str(x))))
word_count

0        0
1        0
2        0
3        0
4        0
        ..
74676    0
74677    0
74678    0
74679    0
74680    0
Name: im getting on borderlands and i will murder you all ,, Length: 74681, dtype: int64

In [26]:
word_count.sum()

np.int64(79)

In [27]:
data.iloc[word_count.argmax()]

2401                                                                                                                                                                2713
Borderlands                                                                                                                                                  Borderlands
Positive                                                                                                                                                         Neutral
im getting on borderlands and i will murder you all ,    Stream on Borderlands 3 tonight at 8pm! Come and say hello, it's always a pleasure to watch on the stream guys.
Name: 1782, dtype: object

> The total amount of the word 'hello' in the data is 79. I checked one instance using the argmax() function.

# 2. Find  a specific special character and number of occurrences

In [30]:
# Check for '!' special character

word_count = data.iloc[:, 3].apply(lambda x : len(re.findall('!', str(x))))
word_count

0        0
1        0
2        0
3        0
4        0
        ..
74676    0
74677    0
74678    0
74679    0
74680    0
Name: im getting on borderlands and i will murder you all ,, Length: 74681, dtype: int64

In [31]:
word_count.sum()

np.int64(29426)

In [32]:
data.iloc[word_count.argmax()]

2401                                                                                                                                                                                                                                                                                                            10102
Borderlands                                                                                                                                                                                                                                                                         PlayerUnknownsBattlegrounds(PUBG)
Positive                                                                                                                                                                                                                                                                                                     Positive
im getting on borderlands and i will murder you all ,    Thanks to everyone who came and hang out. Thanks for all the support!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Name: 42559, dtype: object

> There is a lot of people who used '!' in their tweets. The sample datapoint is gathered to find which datapoint have the highest amount of '!'

# 3. Find ALL numeric characters  and number of occurrences

In [33]:
# Check for '!' special character

word_count = data.iloc[:, 3].apply(lambda x : len(re.findall('[0-9]', str(x))))
word_count

0        0
1        0
2        0
3        1
4        0
        ..
74676    1
74677    1
74678    1
74679    1
74680    1
Name: im getting on borderlands and i will murder you all ,, Length: 74681, dtype: int64

In [34]:
word_count.sum()

np.int64(110711)

In [35]:
data.iloc[word_count.argmax()]

2401                                                                                                                                                                                                                                                   4014
Borderlands                                                                                                                                                                                                                                           CS-GO
Positive                                                                                                                                                                                                                                            Neutral
im getting on borderlands and i will murder you all ,    @ohnePixel is steam : / / 6 rungame / 730 / 4 76561202255233023 / + 5 csgo _ 3 econ _ action _ year preview % 01 20M2969495601250914043A17575857549D7110843977868000967 to 370€ for good on price?
Name: 21111, dtype: object

> For this part, I simply used [0-9] to just get all the instance of numbers. In each datapoints.

# 4. Find ALL URLs and remove the URLs.

In [45]:
# Check for URLs special character
filter = r"https?://[^\s]+|www\.[^\s]+|bit\.ly/[^\s]+|ttps?://[^\s]+"
word_count = data.iloc[:, 3].apply(lambda x : len(re.findall(filter,
                                                             str(x))))
word_count

0        0
1        0
2        0
3        0
4        0
        ..
74676    0
74677    0
74678    0
74679    0
74680    0
Name: im getting on borderlands and i will murder you all ,, Length: 74681, dtype: int64

In [46]:
word_count.sum()

np.int64(1927)

In [47]:
idx_with_url = word_count.argmax()

In [48]:
data.iloc[idx_with_url]

2401                                                                                                                                                                                                                                                                                                        324
Borderlands                                                                                                                                                                                                                                                                                              Amazon
Positive                                                                                                                                                                                                                                                                                                Neutral
im getting on borderlands and i will murder you all ,    for baby armys who just joined our fandom, welcome to the most exciting fandom ever, BTS loves yall so they discounted  . . Amazon: bit.ly/7Amazon . iTunes: bit.ly/MOTS7iTunes (0.69$) . Google Play: bit.ly/7GooglePlay. BTS Music S: bit.ly/7BigHit
Name: 6527, dtype: object

In [51]:
filter = r"https?://[^\s]+|www\.[^\s]+|bit\.ly/[^\s]+|ttps?://[^\s]+"
clean_data = data.iloc[:, 3].apply(lambda x : re.sub(filter, "",
                                                     str(x)))
clean_data

0                                                                                                                    I am coming to the borders and I will kill you all,
1                                                                                                                     im getting on borderlands and i will kill you all,
2                                                                                                                    im coming on borderlands and i will murder you all,
3                                                                                                              im getting on borderlands 2 and i will murder you me all,
4                                                                                                                  im getting into borderlands and i can murder you all,
                                                                                      ...
74676                                   Just realized that the Windows partition of my Mac is like 6 years behind Nvidia drivers and I have no idea how I did not notice
74677                                              Just realized that my Mac window partition is 6 years behind on Nvidia drivers and I have no idea how I didn't notice
74678                                      Just realized the windows partition of my Mac is now 6 years behind on Nvidia drivers and I have no idea how he didn’t notice
74679    Just realized between the windows partition of my Mac is like being 6 years behind on Nvidia drivers and cars I have no fucking idea how I ever didn ’ t notice
74680                                            Just like the windows partition of my Mac is like 6 years behind on its drivers So you have no idea how I didn’t notice
Name: im getting on borderlands and i will murder you all ,, Length: 74681, dtype: object

In [52]:
clean_data.iloc[idx_with_url]

'for baby armys who just joined our fandom, welcome to the most exciting fandom ever, BTS loves yall so they discounted  . . Amazon:  . iTunes:  (0.69$) . Google Play:  BTS Music S: '

> For this part, instead of just detecting https://, I added bit.ly because at my first execution. The bit.ly and other links are not deleted.